# Generated by Django 5.0 on 2023-12-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='is_verified',
        ),
    ]
